server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

db:
  username		: ${db.username}
  password		: ${db.password}

api:
  username	: ${api.username}
  password	: ${api.password}

spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
                mode: none
